### ISSUE TITLE
Cannot read property '0' of undefined at Parser.decl

### ISSUE THREAD

**Issue by equinusocio** [postcss/postcss-scss#60] opened 2017-05-12 10:05 UTC
I get an error when typing `:host` and `:root`selectors:

```
TypeError: Cannot read property '0' of undefined at Parser.decl (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:203:25) at Parser.other (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:170:18) at Parser.loop (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:81:26) at parse (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/
```

**More info here:**
https://github.com/shinnn/vscode-stylelint/issues/65#issuecomment-292880983

> This is a bug of the upstream project.
```js
'use strict';

const stylelint = require('stylelint');

stylelint.lint({
  code: ':',
  syntax: 'scss',
  config: {
    rules: {}
  }
}).catch(err => console.error(err));
```
```
node ./example.js

TypeError: Cannot read property '0' of undefined
    at ScssParser.decl (/***/node_modules/postcss/lib/parser.js:203:25)
    at ScssParser.other (/***/node_modules/postcss/lib/parser.js:170:18)
    at ScssParser.loop (/***/node_modules/postcss/lib/parser.js:81:26)
    at scssParse (/***/node_modules/postcss-scss/lib/scss-parse.js:21:12)
    at new LazyResult (/Users/shinnn/github/vscode-stylelint/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/***/node_modules/postcss/lib/processor.js:117:12)
    at getCode.then.code (/***/node_modules/stylelint/lib/getPostcssResult.js:83:29)
```
> In this case, `stylelint.lint()` must be rejected with `CssSyntaxError` rather than `TypeError`

**Related Issues:**
- https://github.com/shinnn/vscode-stylelint/issues/65#issuecomment-292880983
- https://github.com/shinnn/vscode-stylelint/issues/66#issuecomment-293020911
- https://github.com/shinnn/vscode-stylelint/issues/73

**Comment by shinnn** [comment] 2017-05-12 10:09
Duplicate of https://github.com/postcss/postcss-scss/issues/57

**Closed by shinnn** 2017-05-12 10:09 UTC

**Comment by ai** [comment] 2017-05-12 23:05
I think stylelint still use old PostCSS. Make sure that it is latest 6.0.
